### ISSUE TITLE
Error: unhandled exception: invalid integer:  [ValueError]

### ISSUE THREAD

**Issue by DartCrusaderBn** [geekrelief/gdnim#11] opened 2021-01-09 11:38 UTC
After writting any task in console i see this error:

Error: unhandled exception: invalid integer:  [ValueError]

**Comment by geekrelief** [comment] 2021-01-09 17:50
This issue report is useless for debugging.  Please provide the steps to reproduce, the output vs expected output.

**Comment by DartCrusaderBn** [comment] 2021-01-10 08:47
I installed **Other Dependencies**, and i writted ./build help (after building custom-build of godot and building build.nim) but i getting this error: **Error: unhandled exception: invalid integer: [ValueError]**

**Comment by geekrelief** [comment] 2021-01-11 05:46
Did you modify `build.ini` for your setup?
Try modifying `build.nim.cfg` by replacing `d:release` with  `--debugger:native --stackTrace:on` so you get a line number for the error.

**Comment by DartCrusaderBn** [comment] 2021-01-11 06:04
yes, i modified `build.ini` paths to ~~my project~~ app folder and `godot-3.2_custom`

```
[Godot]
src=r"C:\Users\User\Documents\godot_custom\godot-3.2_custom"
base_branch="3.2"
build_branch="3.2_custom"
merge_branches="3.2_script_data_error, 3.2_gdnative_unload, 3.2_filter_import"
platform="windows"
bits="64"
bin=r"C:\Users\User\Documents\godot_custom\godot-3.2_custom\bin\godot.windows.opt.tools.64.exe"
tools_debug_bin=r"C:\Users\User\Documents\godot_custom\godot-3.2_custom\bin\godot.windows.tools.64.exe"
tools_release_bin=r"C:\Users\UserDocuments\godot_custom\godot-3.2_custom\bin\godot.windows.opt.tools.64.exe"
```
and
```
[Dir]
# godot project directory
app="C:\Users\User\Documents\gdnim-master\gdnim-master\app"
# your components that hot reload
comps="C:\Users\User\Documents\gdnim-master\gdnim-master\components"
# location of the godot api, move to parent directory to make it shareable
deps="C:\Users\User\Documents\gdnim-master\gdnim-master\deps"
deps_godot="C:\Users\User\Documents\gdnim-master\gdnim-master\deps\godot"
```
and now i'm still getting this error
```
C:\Users\User\Documents\gdnim-master\gdnim-master\tasks.nim(65) build
C:\Users\User\apps\nim\current\lib\pure\strutils.nim(1115) parseInt
Error: unhandled exception: invalid integer:  [ValueError]
```

**Comment by geekrelief** [comment] 2021-01-11 06:35
The error is complaining about a bad value for `cwatch_interval`  What is the value in your build.ini? It should be an integer representing milliseconds.

**Comment by DartCrusaderBn** [comment] 2021-01-11 07:21
it's default (`cwatch_interval = 300`)

**Comment by geekrelief** [comment] 2021-01-11 09:53
This isn't making any sense to me. What does config.getSectionValue("Builld", "cwatch_interval") return? What version of nim are you running?

**Comment by DartCrusaderBn** [comment] 2021-01-11 09:59
Nim Compiler Version 1.4.2

**Comment by geekrelief** [comment] 2021-01-11 10:01
I can't reproduce the issue on my end.  And several others have been able to run the setup process with out any issue.  You're going to have to debug this.  Try modifying `tasks.nim` to see what's going on.

**Comment by geekrelief** [comment] 2021-01-11 10:07
The only other thing I can suggest is running using nim version: 3b963a81 which is the version I'm on.

**Comment by DartCrusaderBn** [comment] 2021-01-11 10:15
but where i can find this version?

**Comment by geekrelief** [comment] 2021-01-11 10:26
https://github.com/nim-lang/Nim

**Comment by geekrelief** [comment] 2021-01-11 10:28
Honestly, you should try debugging without resorting to that version.

**Comment by DartCrusaderBn** [comment] 2021-01-11 16:07
i builded 3b963a81 source of nim, but unfortunaly, it's not helped (i changed `bin` folder files of 3b963a81 nim to shims folder). Trying to rebuild with `--debugger:native --stackTrace:on` i got this error: `Error: cannot open 'C:\Users\User\lib\system.nim'`

trying to find the solution, i only found solution for Mac OS, but i don't know is it works for Windows

**Comment by geekrelief** [comment] 2021-01-11 16:39
Again.
> I can't reproduce the issue on my end. And several others have been able to run the setup process with out any issue. You're going to have to debug this. Try modifying `tasks.nim` to see what's going on.

**Comment by geekrelief** [comment] 2021-01-24 05:34
Closing.  Cannot repro.

**Closed as completed by geekrelief** 2021-01-24 05:34 UTC
